name: "E2E Deployment testing workflow"
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
     runs-on: [ E2E-test-linux ]

     steps:
      - name: install
        run: |
          sudo apt-get update
          sudo apt-get install -qqy awscli jq openjdk-11-jdk
      - name: unit testing
        run: |
          echo "unit testing stage"
      - name: build
        run: |
          echo "build stage"
      - name: pop
        run: |
          echo "Pop stage"
      - name: download e2e artifacts
        run: exit 1
          
      - name: e2e_tests_linux
        if: always()
        run: echo "E2E Tests for Linux"

      - name: e2e_tests_mac
        if: always()
        run: echo "E2E Tests for Mac"
        run: exit 1

      - name: e2e_tests_windows
        if: always()
        run: echo "E2E Tests for Linux"

      - name: Archive results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-output
          path: test-output
      - name: publish
        run: |
          echo "publish stage"
    

