name: action version 1.0
on:
  workflow_dispatch:
    inputs:
      TAG_NAME:
        description: Version'
      root = true
env:
  TAG_NAME: ${{ github.event.inputs.TAG_NAME || github.event.release.tag_name }}
permissions:
  contents: write

jobs:
  update_tag:
    runs-on: [self-hosted, kk]
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: setup git config
        
      - name: Update the version
        run: 
          echo ${{ env.TAG_NAME }}
         
          npm ci
          npm version ${{ env.TAG_NAME }}
      - uses: actions/upload-artifact@v6
        with:
          path: %TARGET%
