name: synopsys-action

on:
  push:
    branches: [ SIGINT-1438-build_unittest_coverage ]

jobs:
  build:
    runs-on:
      group: sig-default
      labels: linux
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: npm install
#      - name: Code Coverage
#        run: npm test -- --coverage --collectCoverageFrom='src/**/*.{ts,jxs}'
      - name: Unit Tests
        run: npm run all
#      - name: Contract Tests
#        run: npm run all
