name: synopsys-action

on:
  push:
    branches: [ SIGINT-1438-build_unittest_coverage ]

jobs:
  build:
    runs-on: [E2E-test-npm]
      # group: sig-default
      # labels: linux
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3
      - name: Install Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: setup gcloud
        run: |
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
            echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            sudo apt-get update && sudo apt-get install -y google-cloud-sdk
            
      - name: Authenticate with Google Cloud
        run: echo "${GCP_SA_KEY}"  > "${HOME}/gcp-key.json"
      - name: create npmrc file
        run: echo "${NPM}" > "${HOME}/.npmrc"
      - name: Set Google Cloud credentials
        run: gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
      - name: Install Dependencies
        run: |
          npm ci
#          pwd
#          sudo rm package-lock.json
#          npm install --package-lock
#          sudo cat package-lock.json
#          sleep 300000
# #         npm install
# #         npm install eslint-plugin-prettier@4.2.1 --save-dev
# #          npm install --package-lock
# #          npm install eslint-plugin-prettier@latest --save-dev
# #          sudo cat package-lock.json
# #         sudo cd /root/.npmrc
# #         sudo cat npmrc
# #          npm ci
# #      - name: Code Coverage
# #        run: npm test -- --coverage --collectCoverageFrom='src/**/*.{ts,jxs}'
#       - name: Unit Tests
#         run: npm run all
#       - name: Contract Tests
#         run: npm run contract-test
    #   # analysis:
    # steps:
    #   - name: Checkout Source
    #     uses: actions/checkout@v3
    #   - name: pop_polaris
    #     uses: synopsys-sig/synopsys-action@v1.6.0
    #     with:
    #       polaris_server_url: ${{ secrets.POLARIS_SERVERURL }}
    #       polaris_access_token: ${{ secrets.POLARIS_ACCESSTOKEN }}
    #       polaris_application_name: node-goat-1
    #       polaris_project_name: node-goat-1
    #       polaris_assessment_types: "SAST"
          
      # - name: pop_blackduck
      #   if: always()
      #   uses: synopsys-sig/synopsys-action@v1.2.0
      #   env:
      #     DETECT_PROJECT_NAME: spurohitsynopsys-${{ github.event.repository.name }}
      #     DETECT_PROJECT_VERSION_NAME: ${{ github.event.repository.name }}-${{needs.versioning.outputs.synopsys-action-version}}
      #   with:
      #     blackduck_url: ${{ secrets.BLACKDUCK_URL }}
      #     blackduck_apiToken: ${{ secrets.BLACKDUCK_API_TOKEN }}
